fix: semver pipeline

diff --git a/task/semver/semver.yaml b/task/semver/semver.yaml
--- a/task/semver/semver.yaml
+++ b/task/semver/semver.yaml
@@ -1,26 +1,41 @@
 apiVersion: tekton.dev/v1beta1
-kind: Task
+kind: PipelineRun
 metadata:
+  creationTimestamp: null
   name: semver
-  spec:
-  stepTemplate:
-    resources:
-      requests:
-        cpu: 100m
-        memory: 128Mi
-    workingDir: /workspace/source
-  steps:
-    - script: |
-        #!/usr/bin/env sh
-        last_message="$(git log --no-merges -1 --pretty=%B)"
-        echo "Last commit message is: $last_message."
-        (
-        case $last_message in
-          "fix:"*) echo "Contains SemVer release info" && exit 0 ;;
-          "feat:"*) echo "Contains SemVer release info" && exit 0 ;;
-          "BREAKING CHANGE:"*) echo "Contains SemVer release info" && exit 0 ;;
-          *)  echo "Missing SemVer release info" && exit 1  ;;
-        esac
-        )
-      image: alpine/git
-      name: semver-check
+spec:
+  pipelineSpec:
+    tasks:
+      - name: from-build-pack
+        resources: {}
+        taskSpec:
+          metadata: {}
+          stepTemplate:
+            env:
+              - name: HOME
+                value: /tekton/home
+            name: ""
+            resources:
+              requests:
+                cpu: 200m
+                memory: 256Mi
+            workingDir: /workspace/source
+          steps:
+            - script: |
+                #!/usr/bin/env sh
+                last_message="$(git log --no-merges -1 --pretty=%B)"
+                echo "Last commit message is: $last_message."
+                (
+                case $last_message in
+                  "fix:"*) echo "Contains SemVer release info" && exit 0 ;;
+                  "feat:"*) echo "Contains SemVer release info" && exit 0 ;;
+                  "BREAKING CHANGE:"*) echo "Contains SemVer release info" && exit 0 ;;
+                  *)  echo "Missing SemVer release info" && exit 1  ;;
+                esac
+                )
+              image: alpine/git
+              name: semver-check
+  podTemplate: {}
+  serviceAccountName: tekton-bot
+  timeout: 12h0m0s
+status: {}
